### ISSUE TITLE
How to add mods on MineTest?

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.minetest.Minetest#6] opened 2018-08-02 10:44 UTC
Hello, i want to know how can i add mods, because the paste button is disabled on minetest’s game folder. Any solution? (I get minetest from Apps Center)
PS: Sorry but i know this is off-topic.

@nedrichards Could help? Topic: [https://community.endlessos.com/t/how-to-add-mods-on-minetest/7268](https://community.endlessos.com/t/how-to-add-mods-on-minetest/7268?u=leandrostanger)

**Comment by cpba** [comment] 2018-10-09 15:17
@LeandroStanger I haven't actually tried to use any mods, but given that the manifest uses `--persist=.minetest` you should be able to install mods the usual way by dropping them in `~/.var/app/net.minetest.Minetest/.minetest/` rather than `~/.minetest`.

**Comment by koenigjaeger** [comment] 2019-02-10 21:22
I'll add that I had to manually create a `games` folder in `~/.var/app/net.minetest.Minetest/.minetest/` but it did work.

**Comment by sofar** [comment] 2019-07-24 02:54
This is an old bug where installing mods was a manual thing.

Nowadays Minetest has an in-game menu system that can download and install mods, texture packs and whole games from our central contentdb service.

I just tested it with the 5.0.0 release and this has been functional since then, and is working correctly.

This doesn't need to remain open anymore - the problem is solved without flatpak manifest adjustments needed.

**Comment by cpba** [comment] 2019-07-24 03:31
@sofar The pull request that automatically reopened this issue doesn't offer any explanation, so it was most likely done by mistake while trying to reference something else. I'm pretty sure you can safely close this again.

**Closed** 2019-07-24 03:47 UTC

**Comment by LeandroStanger** [comment] 2019-07-25 20:05
![Captura de tela de 2019-07-25 17-05-08](https://user-images.githubusercontent.com/26097419/61905013-6e7b2080-aefe-11e9-934e-1d7f71e4fff9.png)

**Comment by sofar** [comment] 2019-07-26 02:25
@LeandroStanger is there any noteworthy console output? Can you run it from a terminal?

**Comment by LeandroStanger** [comment] 2019-07-26 10:41
```
2019-07-26 07:40:28: ERROR[Main]: https://content.minetest.net/api/packages/?type=mod&type=game&type=txp&protocol_version=37&hide=nonfree&hide=desktop_default not found (Timeout was reached) (response code 0)

```

**Comment by sofar** [comment] 2019-08-05 01:56
That would indicate a network issue. It could be temporary, or it could be local to your system.

```
2019-08-04 18:55:24: ACTION[Main]: Installed package to /home/sofar/.minetest/mods/moreores
```

Still works perfectly fine for me. Maybe someone else can check. It's entirely possible contendb was down while you tried.
